### ISSUE TITLE
Error while porting the cpp-ethereum-cross on Tizen 3.0 TV platform

### ISSUE THREAD

**Issue by ydvsam** [doublethinkco/cpp-ethereum-cross#123]
Dear All,

I'm new to ethereum platform and want to develop decentralized app on Tizen 3.0 for TV profile on ethereum platform.
After going through many threads, I came to know that I have to do following things...

1) Cross compile to "cpp-ethereum-cross" for Tizen 3.0 TV profile.
2) Install  cpp-ethereum-cross on Tizen 3.0 TV profile.
3) I will create frontend in JavaScript, that will interact with cpp-ethereum for account management of ether.

We have already created one small DApp on our PC using geth and JavaScript, now We want to move our idea over Tizen 3.0 TV profile.

While executing the below commands, 
 a) git clone https://github.com/doublethinkco/webthree-umbrella-cross.git 
 b) sudo ./build-armel.sh / sudo ./build-armhf.sh / sudo ./build-armel-apt.sh / sudo ./build-armhf-apt.sh

Following error appear...

 $sudo ./build-armel-apt.sh
 ./build-generic.sh: line 31: docker: command not found

I've following queries
1) Is my understanding correct about the above 3 points ?
2) How can I resolve the above error for cross compiling the cpp-ethereum-cross for Tizen 3.0 TV profile.
3) If It's feasible(Creating a DApp using ethereum platform) at all on Tizen TV platform ?

I'm using 12.04 Ubuntu OS for cross compilation.

Waiting for your prompt reply.

Thanks in Advance
Sam

**Comment by bobsummerwill** [comment]
Greetings!   Aha, Tizen, my old friend :-)

So getting cpp-ethereum working on a Gear S2 smartwatch was my original motivation for starting on cpp-ethereum-cross, but funny enough, I never got it working on Tizen, because of the ancient state of the glibc in Tizen 2.4.     If you are motivated to get to the end of the line on that process then I wish you luck.

The build error you are seeing looks easy enough - looks like you don't have Docker installed and on your path :-)    You will also ONLY need to run ./build-armel-apt.sh.

Before you go too far down this rabbit-hole, though, given that you started with geth a PC, you might want to look into geth cross-builds.    My work on cpp-ethereum-cross has been abandoned for a few months, while @karalabe's work on geth cross-builds is ongoing.   The geth cross-build also has the advantage of being fully statically linked, and might "just work".

See https://github.com/ethereum/go-ethereum/wiki/Cross-compiling-Ethereum
